Repository XNXKTech/laravel-esign, pull requests merged in 2022-03, with the labels that each got.

#2 chore(workflows/insights): remove 8.1
  .github/workflows/insights.yml
Labels: size/XS

#1 chore(deps-dev): add illuminate/support
  composer.json
  composer.lock
Labels: size/XS

#3 chore(env): add testing env
  .env.testing
  .gitignore
Labels: size/XS

#4 refactor(config): app key to secret
  src/Esign.php
  src/config.php
Labels: size/XS

#5 chore(test): add echo secrets
  .github/workflows/tests.yml
Labels: size/XS

#7 feat(token): add signature
  phpinsights.php
  src/Adapter/Guzzle.php
  src/Adapter/JSONException.php
  src/Adapter/ResponseException.php
  src/Auth/Auth.php
  src/Auth/Token.php
  src/Core/AbstractAPI.php
  src/Core/AccessToken.php
  src/Core/Http.php
  src/Endpoints/Account.php
  src/Exceptions/Exception.php
  src/Exceptions/HttpException.php
  src/Exceptions/InternalException.php
  src/Exceptions/InvalidArgumentException.php
  src/Exceptions/RuntimeException.php
  src/Facades/Esign.php
  src/Support/Arr.php
  src/Support/Collection.php
  src/Support/Log.php
  src/helpers.php
  tests/Auth/APIKeyTest.php
Labels: size/XXL

#16 refactor: move to endpoints
  src/Account/Account.php
  src/Endpoints/Account.php
  src/Endpoints/File.php
  src/Endpoints/Identity.php
  src/Endpoints/SignFlow.php
  src/Endpoints/Template.php
  src/Foundation/Config.php
  src/Foundation/ServiceProviders/AccountProvider.php
  src/Foundation/ServiceProviders/FileProvider.php
  src/Foundation/ServiceProviders/IdentityProvider.php
  src/Foundation/ServiceProviders/SignFlowProvider.php
  src/Foundation/ServiceProviders/TemplateProvider.php
Labels: size/XXL

#19 test(endpoints/file): add file test
  src/Adapter/Guzzle.php
  src/Auth/Token.php
  src/Endpoints/File.php
  src/Esign.php
  tests/Endpoints/FileTest.php
  tests/Public/test.pdf
Labels: size/L

#20 test(endpoints/sign): add sign flow
  src/Auth/Token.php
  src/Esign.php
  tests/Endpoints/SignFlowTest.php
Labels: size/M

#22 test(endpoints/sign): add sign flow
  config/esign.php
  src/Adapter/Guzzle.php
  src/Auth/Token.php
  src/Endpoints/SignFlow.php
  tests/Endpoints/SignFlowTest.php
Labels: size/L

#23 feat(esign): add default read env
  src/Esign.php
  tests/TestHelpers.php
Labels: size/XS
